### ISSUE TITLE
opam 2 not in avsm/ppa 

### ISSUE THREAD

**Issue by frank-emrich** [avsm/opam2-ppa#1]
Hi, it seems like opam 2 is not actually in avsm/ppa, but only in avsm/ppa-opam-experimental. I assume that's not intentional?

**Comment by avsm** [comment]
It's because I received no feedback at all on them, as requested here : https://discuss.ocaml.org/t/opam-2-0-experimental-ppas/2446

I guess I'll assume silence to mean that they work...

**Comment by frank-emrich** [comment]
I have just tested the installation on Ubuntu 18.10. 
Installing opam from your PPA then resulted in the following error: 
dpkg: error processing archive /var/cache/apt/archives/opam_2.0.1-0ppa2~cosmic_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/opam-admin.1.gz', which is also in package opam-docs 1.2.2-7

It seems like your opam package subsumes both opam and opam-docs from the Ubuntu repository. Uninstalling opam-docs solved the problem for me, the installation went through just fine after that

**Comment by avsm** [comment]
Thanks! I'm rebuilding them with a `replaces:` field and opam 2.0.1 and will upload to avsm/ppa after that.

**Comment by avsm** [comment]
Ok, avsm/ppa should now have the opam 2.0.1 release :)

**Comment by frank-emrich** [comment]
Thanks, that solved it! :)
Are there any plans to make opam 2 builds available for pre-bionic releases? I know that opam 2 uses bubblewrap, so the default configuration on those earlier releases would have to disable bubblewrap. It seems unfortunate that because of this, opam 2 can't be used with Travis CI (... without resorting to things like docker or install-via-wget). But having a quick look, it seems like there is no easy way (e.g., ./configure switch) to tell opam not to use bubblewrap from a build script

**Comment by avsm** [comment]
you can use `opam init --disable-sandboxing` to remove the need for bubblewrap.  However, it really is easier to use docker via ocaml-ci-scripts rather than building PPAs for older distros -- particularly since in Travis they are deprecating non-container builds.    So, no plans from me to support pre-bionic releases at this stage...
